name: static analysis

on:
  push:
    branches:
      - main
  pull_request:
      - main

jobs:
  autopep8:
    name: Autopep8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install autopep8
      run: |
        pip install autopep8

    - name: Run autopep8
      run: |
        autopep8 --in-place --recursive .
        git diff --exit-code

  pyright:
    name: Pyright
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pyright
      run: |
        pip install pyright

    - name: Run pyright
      run: |
        pyright *.py

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pylint
      run: |
        pip install pylint

    - name: Run pylint
      run: |
        pylint *.py --exit-zero


